---
title: "NOAA earthquake data vignette"
author: "Mathieu JOnes"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# noaaQuake

The goal of noaaQuake is to be a package that contains some functions that helps clean, manipulate and visulaise the earthquakes data

## Examples

### Example 1: cleaning the raw data

```{r example}
library(noaaQuake)

db <- clean_raw_data()

```

### Example 2: visualising a timeline of quakes

```{r example2}
library(ggplot2)
ggplot(db[COUNTRY %in%c("CHINA","GREECE")],
       aes (x = as.Date(DATE), 
            y = COUNTRY, 
            color = as.numeric(DEATHS)/1000, 
            size = as.numeric(EQ_PRIMARY))) +
    geom_timeline(aes(xmin = as.Date("2000-01-01"), xmax = as.Date("2018-01-01"))) +
    geom_timeline_label(n_max = 15, aes(label = LOCATION_NAME, xmin = as.Date("2000-01-01"),
                            xmax = as.Date("2018-01-01")))+
    xlab("Date") + ylab("") + ggtitle("Timeline of Earthquakes") +
    labs(size = "Richter scale", color = "# deaths (k)" )+
    theme_bw() +
    theme(legend.position="bottom")
```

### Example 3: leaflet plot visualising location of quake

```{r}

eq_map(db[COUNTRY %in%c("GREECE") & DATE>"2000-01-01"], annot_col = "popup_text")
```
